name: Stormspotter Build

on: [push]

jobs:
  build:
    name: Stormspotter Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python on ${{ matrix.os }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Shiv
        run: |
          pip install shiv

      - name: Build Stormcollector
        working-directory: stormcollector
        run: |
          python build_collector.py

      - name: Build SSBackend
        working-directory: backend
        run: |
          python build_backend.py

      - name: Upload backend
        uses: actions/upload-artifact@master
        with:
          name: ssbackend-${{ matrix.os }}
          path: backend/ssbackend.pyz

      - name: Upload stormcollector
        uses: actions/upload-artifact@master
        with:
          name: stormcollector-${{ matrix.os }}
          path: stormcollector/stormcollector.zip
