name: Stormspotter Build

on: [push]

jobs:
  build:
    name: Stormspotter Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python on ${{ matrix.os }}
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Shiv
        run: |
          pip install shiv

      - name: Build Stormcollector
        working-directory: stormcollector
        run: |
          python build_collector.py

      - name: Build SSBackend
        working-directory: backend
        run: |
          python build_backend.py

      - name: Build SSFrontend
        working-directory: frontend
        run: |
          npm ci
          quasar build

      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: stormspotter-${{ matrix.os }}
          path: |
            backend/ssbackend.pyz
            stormcollector/sscollector.py
            stormcollector/cloud.cfg
            frontend/dist/spa/
